from django.urls import path
from . import views, ai_views, run_actions, regression, ci_views

app_name = "web_testing"
urlpatterns = [
    path('suites/<int:pk>/ci/', ci_views.settings, name='ci_settings'),
    path('suites/<int:pk>/ci/<str:action>/', ci_views.token_action, name='ci_token_action'),
    path('ci/suites/<int:pk>/runs/', ci_views.runs, name='ci_submit'),
    path('ci/suites/<int:pk>/runs/<uuid:run_id>/', ci_views.runs, name='ci_run'),
    path("defects/<int:pk>/regression/", regression.new, name="regression_new"),
    path("runs/<uuid:pk>/verify-regression/", regression.verify, name="regression_verify"),
    path("products/<int:product_id>/ai-requests/new/", ai_views.generate, name="ai_generate"),
    path("ai-requests/<int:pk>/", ai_views.detail, name="ai_detail"),
    path("ai-requests/<int:pk>/import/", ai_views.import_selected, name="ai_import"),
    path("ai-drafts/<int:pk>/review/", ai_views.review, name="ai_review"),
    path("environments/", views.environments, name="environments"),
    path("environments/new/", views.edit_environment, name="environment_new"),
    path("environments/<int:pk>/", views.edit_environment, name="environment_edit"),
    path("cases/", views.cases, name="cases"),
    path("cases/new/", views.edit_case, name="case_new"),
    path("cases/<int:pk>/", views.edit_case, name="case_edit"),
    path("cases/<int:pk>/delete/", views.delete_case, name="case_delete"),
    path("cases/<int:pk>/debug/", run_actions.debug_case, name="case_debug"),
    path("suites/", views.suites, name="suites"),
    path("suites/new/", views.edit_suite, name="suite_new"),
    path("suites/<int:pk>/", views.edit_suite, name="suite_edit"),
    path("suites/<int:pk>/delete/", views.delete_suite, name="suite_delete"),
    path("suites/<int:pk>/execute/", views.submit, name="submit"),
    path("runs/", views.runs, name="runs"),
    path("runs/<uuid:pk>/", views.run_detail, name="run"),
    path("runs/<uuid:pk>/status/", views.status, name="status"),
    path("runs/<uuid:pk>/cancel/", views.cancel, name="cancel"),
    path("runs/<uuid:pk>/retry/", views.retry, name="retry"),
    path("screenshots/<int:pk>/", views.screenshot, name="screenshot"),
]
