# Generated by Django 6.0.8 on 2026-10-02 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0013_remove_initial_qa_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('folder', models.CharField(blank=True, help_text='例如：登录/异常场景', max_length=200, verbose_name='目录')),
                ('description', models.TextField(blank=True, verbose_name='前置条件与说明')),
                ('steps_encrypted', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
            ],
            options={
                'ordering': ('folder', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='WebSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('base_url', models.CharField(max_length=500, verbose_name='测试站点')),
                ('case_ids', models.JSONField(default=list)),
                ('ignore_https_errors', models.BooleanField(default=False, verbose_name='允许测试站点使用自签名证书')),
                ('stop_on_failure', models.BooleanField(default=False, verbose_name='失败后停止')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
            ],
        ),
        migrations.CreateModel(
            name='WebRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('submission_token', models.UUIDField()),
                ('snapshot_encrypted', models.TextField()),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '执行异常'), ('cancelled', '已取消'), ('interrupted', '执行中断')], default='queued', max_length=16)),
                ('total', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('heartbeat', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_testing.webrun')),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_testing.websuite')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='WebResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=16)),
                ('steps', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('screenshot', models.BinaryField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='web_testing.webrun')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('run', 'position'), name='web_result_position_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='webrun',
            constraint=models.UniqueConstraint(fields=('owner', 'submission_token'), name='web_run_submission_unique'),
        ),
    ]
