# Generated by Django 6.0.8 on 2026-10-02 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('zh-hans', '简体中文'), ('en', 'English')], default='zh-hans', max_length=16, verbose_name='界面语言')),
                ('time_zone', models.CharField(choices=[('Asia/Shanghai', '北京时间（UTC+8）'), ('Etc/UTC', '协调世界时（UTC）')], default='Asia/Shanghai', max_length=64, verbose_name='显示时区')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preference', to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
        ),
    ]
