# Generated by Django 6.0.8 on 2026-08-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('requirement', models.TextField(verbose_name='需求描述')),
                ('result', models.TextField(blank=True, verbose_name='AI生成结果')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI请求',
                'verbose_name_plural': 'AI请求',
            },
        ),
    ]
