# Generated by Django 6.0.8 on 2026-08-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('testcases', '0024_alter_testcase_extra_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='testcases.category', verbose_name='目标分类'),
        ),
        migrations.CreateModel(
            name='AITestCaseDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, verbose_name='用例编号')),
                ('summary', models.CharField(max_length=255, verbose_name='用例标题')),
                ('priority', models.CharField(default='P3', max_length=8, verbose_name='优先级')),
                ('test_type', models.CharField(blank=True, max_length=64, verbose_name='测试类型')),
                ('preconditions', models.JSONField(blank=True, default=list, verbose_name='前置条件')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='测试步骤')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('imported_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_source_draft', to='testcases.testcase', verbose_name='已导入用例')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='ai_assistant.airequest', verbose_name='AI请求')),
            ],
            options={
                'verbose_name': 'AI测试用例草稿',
                'verbose_name_plural': 'AI测试用例草稿',
                'ordering': ('id',),
            },
        ),
    ]
