# Generated by Django 6.0.8 on 2026-08-30 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_legacy_requests(apps, schema_editor):
    AIRequest = apps.get_model("ai_assistant", "AIRequest")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    owner = User.objects.filter(is_superuser=True).order_by("pk").first()
    if owner is None:
        owner = User.objects.order_by("pk").first()
    if owner is not None:
        AIRequest.objects.filter(created_by__isnull=True).update(created_by=owner)


def unassign_legacy_requests(apps, schema_editor):
    AIRequest = apps.get_model("ai_assistant", "AIRequest")
    AIRequest.objects.update(created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_airequest_category_aitestcasedraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.RunPython(assign_legacy_requests, unassign_legacy_requests),
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('api_base', models.URLField(max_length=500, verbose_name='API 地址')),
                ('model', models.CharField(max_length=200, verbose_name='模型名称')),
                ('timeout', models.PositiveIntegerField(default=300, verbose_name='超时时间（秒）')),
                ('api_key_encrypted', models.TextField(blank=True, verbose_name='加密后的 API 密钥')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前启用')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_model_configs', to=settings.AUTH_USER_MODEL, verbose_name='所属账号')),
            ],
            options={
                'verbose_name': 'AI 模型配置',
                'verbose_name_plural': 'AI 模型配置',
                'ordering': ('-is_active', 'name'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_ai_model_name_per_owner')],
            },
        ),
    ]
