# Generated by Django 6.0.8 on 2026-08-31 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_airequest_created_by_aimodelconfig'),
        ('testcases', '0024_alter_testcase_extra_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITestCaseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='质量评分')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='优点')),
                ('issues', models.JSONField(blank=True, default=list, verbose_name='问题')),
                ('missing_scenarios', models.JSONField(blank=True, default=list, verbose_name='缺失场景')),
                ('optimized_summary', models.CharField(max_length=255, verbose_name='优化后标题')),
                ('optimized_preconditions', models.JSONField(blank=True, default=list, verbose_name='优化后前置条件')),
                ('optimized_steps', models.JSONField(blank=True, default=list, verbose_name='优化后步骤')),
                ('raw_result', models.TextField(blank=True, verbose_name='AI 原始结果')),
                ('original_summary', models.CharField(max_length=255, verbose_name='原始标题快照')),
                ('original_text', models.TextField(blank=True, verbose_name='原始正文快照')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='应用时间')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_ai_test_case_reviews', to=settings.AUTH_USER_MODEL, verbose_name='应用人')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_case_reviews', to='ai_assistant.aimodelconfig', verbose_name='使用的模型配置')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_test_case_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评审账号')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='testcases.testcase', verbose_name='正式测试用例')),
            ],
            options={
                'verbose_name': 'AI 测试用例评审',
                'verbose_name_plural': 'AI 测试用例评审',
                'ordering': ('-created',),
            },
        ),
    ]
