# Generated by Django 6.0.8 on 2026-08-31 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_aitestcasereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='AI需求分析'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='analysis_model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_analyses', to='ai_assistant.aimodelconfig', verbose_name='需求分析使用的模型配置'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='analysis_raw',
            field=models.TextField(blank=True, verbose_name='AI需求分析原始结果'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='分析时间'),
        ),
    ]
