# Generated by Django 6.0.8 on 2026-09-01 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_airequest_analysis_airequest_analysis_model_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='coverage_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='AI用例覆盖分析'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='coverage_analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='覆盖分析时间'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='coverage_model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_analyses', to='ai_assistant.aimodelconfig', verbose_name='覆盖分析使用的模型配置'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='coverage_raw',
            field=models.TextField(blank=True, verbose_name='AI用例覆盖分析原始结果'),
        ),
    ]
