# Generated by Django 6.0.8 on 2026-09-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_airequest_coverage_analysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100, verbose_name='配置名称快照')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型名称快照')),
                ('operation', models.CharField(choices=[('requirement_analysis', '需求分析'), ('test_case_generation', '生成测试用例'), ('coverage_analysis', '覆盖率分析'), ('coverage_supplement', '补充覆盖缺口'), ('test_case_review', '测试用例评审'), ('connection_test', '模型连接测试'), ('other', '其他')], max_length=40, verbose_name='操作类型')),
                ('status', models.CharField(choices=[('success', '成功'), ('error', '失败')], max_length=16, verbose_name='调用状态')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时（毫秒）')),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='输入 Token')),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='输出 Token')),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='总 Token')),
                ('error_message', models.TextField(blank=True, verbose_name='错误摘要')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='ai_assistant.aimodelconfig', verbose_name='模型配置')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='所属账号')),
            ],
            options={
                'verbose_name': 'AI 调用记录',
                'verbose_name_plural': 'AI 调用记录',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['owner', '-created'], name='ai_usage_owner_created')],
            },
        ),
    ]
