# Generated by Django 6.0.8 on 2026-09-01 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_aiusagelog'),
        ('testruns', '0020_testexecutiontag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='operation',
            field=models.CharField(choices=[('requirement_analysis', '需求分析'), ('test_case_generation', '生成测试用例'), ('coverage_analysis', '覆盖率分析'), ('coverage_supplement', '补充覆盖缺口'), ('test_case_review', '测试用例评审'), ('test_run_analysis', '测试运行分析'), ('connection_test', '模型连接测试'), ('other', '其他')], max_length=40, verbose_name='操作类型'),
        ),
        migrations.CreateModel(
            name='AITestRunAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_snapshot', models.JSONField(default=dict, verbose_name='执行结果快照')),
                ('result', models.JSONField(default=dict, verbose_name='AI运行分析')),
                ('raw_result', models.TextField(blank=True, verbose_name='AI原始结果')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_run_analyses', to='ai_assistant.aimodelconfig', verbose_name='使用的模型配置')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_test_run_analyses', to=settings.AUTH_USER_MODEL, verbose_name='分析账号')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='testruns.testrun', verbose_name='测试运行')),
            ],
            options={
                'verbose_name': 'AI 测试运行分析',
                'verbose_name_plural': 'AI 测试运行分析',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['owner', 'test_run', '-created'], name='ai_run_owner_created')],
            },
        ),
    ]
