# Generated by Django 6.0.8 on 2026-09-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0008_alter_aiusagelog_operation_aitestrunanalysis"),
        ("linkreference", "0002_update_fields"),
        ("testruns", "0020_testexecutiontag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusagelog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("requirement_analysis", "需求分析"),
                    ("test_case_generation", "生成测试用例"),
                    ("coverage_analysis", "覆盖率分析"),
                    ("coverage_supplement", "补充覆盖缺口"),
                    ("test_case_review", "测试用例评审"),
                    ("test_run_analysis", "测试运行分析"),
                    ("defect_draft_generation", "生成缺陷草稿"),
                    ("test_report_generation", "生成测试报告"),
                    ("connection_test", "模型连接测试"),
                    ("other", "其他"),
                ],
                max_length=40,
                verbose_name="操作类型",
            ),
        ),
        migrations.CreateModel(
            name="AIDefectDraft",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="缺陷标题")),
                ("severity", models.CharField(choices=[("critical", "致命"), ("high", "严重"), ("medium", "一般"), ("low", "轻微")], default="medium", max_length=16, verbose_name="严重程度")),
                ("description", models.TextField(blank=True, verbose_name="问题描述")),
                ("preconditions", models.JSONField(blank=True, default=list, verbose_name="前置条件")),
                ("reproduction_steps", models.JSONField(blank=True, default=list, verbose_name="复现步骤")),
                ("expected_result", models.TextField(blank=True, verbose_name="预期结果")),
                ("actual_result", models.TextField(blank=True, verbose_name="实际结果")),
                ("environment", models.TextField(blank=True, verbose_name="测试环境")),
                ("evidence", models.JSONField(blank=True, default=list, verbose_name="直接证据")),
                ("likely_causes", models.JSONField(blank=True, default=list, verbose_name="待验证的可能原因")),
                ("raw_result", models.TextField(blank=True, verbose_name="AI 原始结果")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="生成时间")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("execution", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_defect_drafts", to="testruns.testexecution", verbose_name="失败执行")),
                ("linked_reference", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_defect_draft", to="linkreference.linkreference", verbose_name="已关联缺陷")),
                ("model_config", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="defect_drafts", to="ai_assistant.aimodelconfig", verbose_name="使用的模型配置")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_defect_drafts", to=settings.AUTH_USER_MODEL, verbose_name="所属账号")),
            ],
            options={"verbose_name": "AI 缺陷草稿", "verbose_name_plural": "AI 缺陷草稿", "ordering": ("-created",), "indexes": [models.Index(fields=["owner", "execution", "-created"], name="ai_defect_owner_created")]},
        ),
        migrations.CreateModel(
            name="AITestReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="报告标题")),
                ("summary", models.TextField(verbose_name="执行摘要")),
                ("scope", models.TextField(blank=True, verbose_name="测试范围")),
                ("conclusion", models.TextField(blank=True, verbose_name="测试结论")),
                ("release_decision", models.CharField(choices=[("go", "可以发布"), ("conditional_go", "有条件发布"), ("no_go", "不建议发布")], default="conditional_go", max_length=24, verbose_name="发布结论")),
                ("metrics_snapshot", models.JSONField(default=dict, verbose_name="执行指标快照")),
                ("defect_summary", models.JSONField(blank=True, default=list, verbose_name="缺陷摘要")),
                ("recommendations", models.JSONField(blank=True, default=list, verbose_name="后续建议")),
                ("raw_result", models.TextField(blank=True, verbose_name="AI 原始结果")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="生成时间")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("model_config", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="test_reports", to="ai_assistant.aimodelconfig", verbose_name="使用的模型配置")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_test_reports", to=settings.AUTH_USER_MODEL, verbose_name="所属账号")),
                ("source_analysis", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reports", to="ai_assistant.aitestrunanalysis", verbose_name="来源分析")),
                ("test_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_reports", to="testruns.testrun", verbose_name="测试运行")),
            ],
            options={"verbose_name": "AI 测试报告", "verbose_name_plural": "AI 测试报告", "ordering": ("-created",), "indexes": [models.Index(fields=["owner", "test_run", "-created"], name="ai_report_owner_created")]},
        ),
        migrations.CreateModel(
            name="AIRegressionVerification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("passed", "回归通过"), ("failed", "回归失败"), ("incomplete", "回归未完成")], default="incomplete", max_length=16, verbose_name="验证结论")),
                ("result", models.JSONField(default=dict, verbose_name="比对结果")),
                ("notes", models.TextField(blank=True, verbose_name="人工备注")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="验证时间")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_regression_verifications", to=settings.AUTH_USER_MODEL, verbose_name="所属账号")),
                ("regression_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_regression_results", to="testruns.testrun", verbose_name="回归测试运行")),
                ("source_report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="regression_verifications", to="ai_assistant.aitestreport", verbose_name="来源测试报告")),
            ],
            options={"verbose_name": "AI 回归验证", "verbose_name_plural": "AI 回归验证", "ordering": ("-created",), "indexes": [models.Index(fields=["owner", "source_report", "-created"], name="ai_regress_owner_created")]},
        ),
    ]
