# Generated by Django 6.0.8 on 2026-09-01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0009_defect_report_regression"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("operation", models.CharField(choices=[("requirement_analysis", "需求分析"), ("test_case_generation", "生成测试用例"), ("coverage_analysis", "覆盖率分析"), ("coverage_supplement", "补充覆盖缺口"), ("test_case_review", "测试用例评审"), ("test_run_analysis", "测试运行分析"), ("defect_draft_generation", "生成缺陷草稿"), ("test_report_generation", "生成测试报告"), ("connection_test", "模型连接测试")], max_length=40, verbose_name="任务类型")),
                ("payload", models.JSONField(default=dict, verbose_name="任务参数")),
                ("result", models.JSONField(blank=True, default=dict, verbose_name="任务结果摘要")),
                ("status", models.CharField(choices=[("queued", "排队中"), ("running", "执行中"), ("cancel_requested", "正在取消"), ("completed", "已完成"), ("failed", "失败"), ("cancelled", "已取消")], default="queued", max_length=24, verbose_name="状态")),
                ("progress", models.PositiveSmallIntegerField(default=5, verbose_name="真实进度")),
                ("stage", models.CharField(default="等待后台处理", max_length=120, verbose_name="当前阶段")),
                ("error_message", models.TextField(blank=True, verbose_name="错误摘要")),
                ("result_url", models.CharField(blank=True, max_length=500, verbose_name="结果地址")),
                ("dedupe_key", models.CharField(blank=True, db_index=True, max_length=255, verbose_name="防重复键")),
                ("attempts", models.PositiveSmallIntegerField(default=1, verbose_name="尝试次数")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="提交时间")),
                ("started", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("heartbeat", models.DateTimeField(blank=True, null=True, verbose_name="心跳时间")),
                ("completed", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("model_config", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="jobs", to="ai_assistant.aimodelconfig", verbose_name="模型配置")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_jobs", to=settings.AUTH_USER_MODEL, verbose_name="所属账号")),
            ],
            options={
                "verbose_name": "AI 后台任务",
                "verbose_name_plural": "AI 后台任务",
                "ordering": ("-created",),
                "indexes": [models.Index(fields=["status", "created"], name="ai_job_status_created"), models.Index(fields=["owner", "-created"], name="ai_job_owner_created")],
            },
        ),
    ]
