# Generated by Django 6.0.8 on 2026-09-01 16:51

import django.db.models.deletion
import hashlib
import json
import re
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_lifecycle_data(apps, schema_editor):
    AIRequest = apps.get_model('ai_assistant', 'AIRequest')
    RequirementVersion = apps.get_model('ai_assistant', 'AIRequirementVersion')
    Defect = apps.get_model('ai_assistant', 'AIDefectDraft')
    Report = apps.get_model('ai_assistant', 'AITestReport')

    for request in AIRequest.objects.all().iterator():
        RequirementVersion.objects.get_or_create(
            request_id=request.pk,
            version=1,
            defaults={
                'title': request.title,
                'requirement': request.requirement,
                'change_summary': '迁移既有需求',
                'changed_by_id': request.created_by_id,
            },
        )
        request.drafts.update(requirement_version=1)

    for defect in Defect.objects.all().iterator():
        text = ' '.join(
            [defect.title, defect.actual_result, defect.expected_result]
            + list(defect.evidence or [])
            + list(defect.likely_causes or [])
        ).lower()
        normalized = re.sub(r'[^\w\u4e00-\u9fff]+', '', text)
        defect.fingerprint = hashlib.sha256(normalized.encode('utf-8')).hexdigest()
        if defect.linked_reference_id:
            defect.status = 'in_progress'
        defect.save(update_fields=('fingerprint', 'status'))

    group_keys = Report.objects.values_list('owner_id', 'test_run_id').distinct()
    for owner_id, test_run_id in group_keys:
        reports = list(
            Report.objects.filter(owner_id=owner_id, test_run_id=test_run_id)
            .order_by('created', 'pk')
        )
        series_uuid = uuid.uuid4()
        previous = None
        for index, report in enumerate(reports, start=1):
            report.series_uuid = series_uuid
            report.version = index
            report.previous_version_id = previous.pk if previous else None
            report.is_current = index == len(reports)
            payload = json.dumps(
                report.metrics_snapshot,
                ensure_ascii=False,
                sort_keys=True,
                separators=(',', ':'),
            )
            report.snapshot_hash = hashlib.sha256(payload.encode('utf-8')).hexdigest()
            report.save(
                update_fields=(
                    'series_uuid', 'version', 'previous_version',
                    'is_current', 'snapshot_hash',
                )
            )
            previous = report


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_aijob'),
        ('management', '0013_remove_initial_qa_contact'),
        ('testruns', '0020_testexecutiontag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidefectdraft',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='aidefectdraft',
            name='closure_reason',
            field=models.TextField(blank=True, verbose_name='关闭原因'),
        ),
        migrations.AddField(
            model_name='aidefectdraft',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='ai_assistant.aidefectdraft', verbose_name='重复于'),
        ),
        migrations.AddField(
            model_name='aidefectdraft',
            name='external_status',
            field=models.CharField(blank=True, max_length=128, verbose_name='外部缺陷状态'),
        ),
        migrations.AddField(
            model_name='aidefectdraft',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='重复识别指纹'),
        ),
        migrations.AddField(
            model_name='aidefectdraft',
            name='fix_version',
            field=models.CharField(blank=True, max_length=128, verbose_name='修复版本'),
        ),
        migrations.AddField(
            model_name='aidefectdraft',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='外部状态同步时间'),
        ),
        migrations.AddField(
            model_name='aidefectdraft',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5')], default='P3', max_length=4, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='aidefectdraft',
            name='status',
            field=models.CharField(choices=[('pending_submission', '待提交'), ('in_progress', '处理中'), ('fixed', '已修复'), ('pending_verification', '待验证'), ('closed', '已关闭')], db_index=True, default='pending_submission', max_length=32, verbose_name='缺陷状态'),
        ),
        migrations.AddField(
            model_name='aidefectdraft',
            name='sync_note',
            field=models.TextField(blank=True, verbose_name='同步说明'),
        ),
        migrations.AddField(
            model_name='airegressionverification',
            name='defect_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regression_verifications', to='ai_assistant.aidefectdraft', verbose_name='来源缺陷'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近变更时间'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='needs_case_review',
            field=models.BooleanField(default=False, verbose_name='需求变更后用例待更新'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='需求版本'),
        ),
        migrations.AddField(
            model_name='aitestcasedraft',
            name='needs_update',
            field=models.BooleanField(default=False, verbose_name='需要随需求更新'),
        ),
        migrations.AddField(
            model_name='aitestcasedraft',
            name='requirement_version',
            field=models.PositiveIntegerField(default=1, verbose_name='来源需求版本'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='approval_comment',
            field=models.TextField(blank=True, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=16, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_test_reports', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='gate_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='发布门禁结果'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True, verbose_name='当前版本'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='ai_assistant.aitestreport', verbose_name='上一版本'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='series_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='报告系列'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='签字确认'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='snapshot_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='快照校验值'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='报告版本'),
        ),
        migrations.AlterField(
            model_name='airegressionverification',
            name='source_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regression_verifications', to='ai_assistant.aitestreport', verbose_name='来源测试报告'),
        ),
        migrations.CreateModel(
            name='AIDefectStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=32, verbose_name='新状态')),
                ('source', models.CharField(choices=[('manual', '人工操作'), ('external_sync', '外部同步'), ('regression', '回归验证'), ('link', '关联缺陷')], default='manual', max_length=24, verbose_name='变更来源')),
                ('reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_defect_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ai_assistant.aidefectdraft', verbose_name='缺陷')),
            ],
            options={
                'verbose_name': 'AI 缺陷状态历史',
                'verbose_name_plural': 'AI 缺陷状态历史',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='AIIterationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='迭代报告标题')),
                ('metrics_snapshot', models.JSONField(default=dict, verbose_name='聚合指标快照')),
                ('run_snapshots', models.JSONField(default=list, verbose_name='各运行快照')),
                ('gate_result', models.JSONField(blank=True, default=dict, verbose_name='发布门禁结果')),
                ('conclusion', models.TextField(blank=True, verbose_name='测试结论')),
                ('release_decision', models.CharField(choices=[('go', '可以发布'), ('conditional_go', '有条件发布'), ('no_go', '不建议发布')], default='conditional_go', max_length=24, verbose_name='发布结论')),
                ('snapshot_hash', models.CharField(blank=True, max_length=64, verbose_name='快照校验值')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_iteration_reports', to=settings.AUTH_USER_MODEL, verbose_name='所属账号')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_iteration_reports', to='management.product', verbose_name='产品')),
                ('runs', models.ManyToManyField(related_name='ai_iteration_reports', to='testruns.testrun', verbose_name='测试运行')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_iteration_reports', to='management.version', verbose_name='版本')),
            ],
            options={
                'verbose_name': 'AI 迭代测试报告',
                'verbose_name_plural': 'AI 迭代测试报告',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='AIReleaseGateRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认发布门禁', max_length=128, verbose_name='规则名称')),
                ('block_priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5')], default='P1', max_length=4, verbose_name='阻断缺陷优先级')),
                ('min_success_rate', models.DecimalField(decimal_places=2, default=95, max_digits=5, verbose_name='最低成功率')),
                ('require_all_executed', models.BooleanField(default=True, verbose_name='要求全部执行')),
                ('max_open_defects', models.PositiveIntegerField(default=0, verbose_name='允许未关闭缺陷数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_release_gate_rules', to=settings.AUTH_USER_MODEL, verbose_name='所属账号')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_release_gate_rules', to='management.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': 'AI 发布门禁规则',
                'verbose_name_plural': 'AI 发布门禁规则',
                'ordering': ('product__name', 'name'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'product', 'name'), name='unique_ai_gate_rule')],
            },
        ),
        migrations.CreateModel(
            name='AIRequirementVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题快照')),
                ('requirement', models.TextField(verbose_name='需求描述快照')),
                ('change_summary', models.CharField(blank=True, max_length=255, verbose_name='变更说明')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requirement_versions', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai_assistant.airequest', verbose_name='需求')),
            ],
            options={
                'verbose_name': 'AI 需求版本',
                'verbose_name_plural': 'AI 需求版本',
                'ordering': ('-version',),
                'constraints': [models.UniqueConstraint(fields=('request', 'version'), name='unique_ai_requirement_version')],
            },
        ),
        migrations.CreateModel(
            name='AITestReportRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(verbose_name='编辑修订号')),
                ('content_snapshot', models.JSONField(default=dict, verbose_name='内容快照')),
                ('change_reason', models.CharField(max_length=255, verbose_name='修改原因')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_report_revisions', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ai_assistant.aitestreport', verbose_name='报告')),
            ],
            options={
                'verbose_name': 'AI 报告修订记录',
                'verbose_name_plural': 'AI 报告修订记录',
                'ordering': ('-created',),
                'constraints': [models.UniqueConstraint(fields=('report', 'revision'), name='unique_ai_report_revision')],
            },
        ),
        migrations.RunPython(backfill_lifecycle_data, noop_reverse),
    ]
