# Generated by Django 6.0.8 on 2026-09-01 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0011_lifecycle_reports_projects'),
        ('management', '0013_remove_initial_qa_contact'),
        ('testruns', '0020_testexecutiontag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='airegressionverification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('defect_draft__isnull', True), ('source_report__isnull', False)), models.Q(('defect_draft__isnull', False), ('source_report__isnull', True)), _connector='OR'), name='ai_regression_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='aireleasegaterule',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', True)), fields=('owner', 'name'), name='unique_default_ai_gate_rule'),
        ),
        migrations.AddConstraint(
            model_name='aitestreport',
            constraint=models.UniqueConstraint(fields=('owner', 'test_run', 'version'), name='unique_ai_report_run_version'),
        ),
        migrations.AddConstraint(
            model_name='aitestreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('owner', 'test_run'), name='unique_current_ai_report_per_run'),
        ),
    ]
