# Generated by Django 6.0.8 on 2026-09-01 17:08

from django.conf import settings
from django.db import migrations, models


def backfill_current_marker(apps, schema_editor):
    Report = apps.get_model('ai_assistant', 'AITestReport')
    keys = Report.objects.values_list('owner_id', 'test_run_id').distinct()
    for owner_id, test_run_id in keys:
        current = (
            Report.objects.filter(
                owner_id=owner_id,
                test_run_id=test_run_id,
                is_current=True,
            )
            .order_by('-version', '-created')
            .first()
        )
        if current is None:
            current = (
                Report.objects.filter(owner_id=owner_id, test_run_id=test_run_id)
                .order_by('-version', '-created')
                .first()
            )
        if current:
            current.current_marker = True
            current.save(update_fields=('current_marker',))


def clear_current_marker(apps, schema_editor):
    apps.get_model('ai_assistant', 'AITestReport').objects.update(current_marker=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0012_lifecycle_integrity'),
        ('testruns', '0020_testexecutiontag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aireleasegaterule',
            name='unique_default_ai_gate_rule',
        ),
        migrations.RemoveConstraint(
            model_name='aitestreport',
            name='unique_current_ai_report_per_run',
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='current_marker',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='当前版本唯一标记'),
        ),
        migrations.RunPython(backfill_current_marker, clear_current_marker),
        migrations.AddConstraint(
            model_name='aitestreport',
            constraint=models.UniqueConstraint(fields=('owner', 'test_run', 'current_marker'), name='unique_current_ai_report_per_run'),
        ),
    ]
