# Generated by Django 6.0.8 on 2026-09-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0013_mariadb_current_report_integrity"),
        ("management", "0013_remove_initial_qa_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectResourceFolder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("requirement", "需求"),
                            ("case", "测试用例"),
                            ("plan", "测试计划"),
                        ],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="目录名称")),
                ("position", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_resource_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ai_assistant.projectresourcefolder",
                        verbose_name="上级目录",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_resource_folders",
                        to="management.product",
                        verbose_name="项目",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_project_resource_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目共享资源目录",
                "verbose_name_plural": "项目共享资源目录",
                "ordering": (
                    "product__name",
                    "resource_type",
                    "position",
                    "name",
                    "pk",
                ),
                "indexes": [
                    models.Index(
                        fields=["product", "resource_type", "parent", "position"],
                        name="shared_folder_tree_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "resource_type", "parent", "name"),
                        name="unique_shared_resource_folder",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectResourceAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("requirement", "需求"),
                            ("case", "测试用例"),
                            ("plan", "测试计划"),
                        ],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(verbose_name="资源编号")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="归档时间")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_resource_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="归档人",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_assignments",
                        to="ai_assistant.projectresourcefolder",
                        verbose_name="共享目录",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目共享资源归档",
                "verbose_name_plural": "项目共享资源归档",
                "indexes": [
                    models.Index(
                        fields=["resource_type", "object_id"],
                        name="shared_resource_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource_type", "object_id"),
                        name="unique_shared_resource_assignment",
                    )
                ],
            },
        ),
    ]
