# Generated by Django 6.0.8 on 2026-09-24 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0017_instruction_profile_project_scope'),
        ('management', '0013_remove_initial_qa_contact'),
        ('testcases', '0024_alter_testcase_extra_link'),
        ('testruns', '0020_testexecutiontag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD')], default='GET', max_length=8, verbose_name='请求方法')),
                ('path', models.CharField(max_length=1000, verbose_name='接口路径')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('query', models.JSONField(blank=True, default=dict, verbose_name='查询参数')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='JSON 请求体')),
                ('send_body', models.BooleanField(default=False, verbose_name='发送 JSON 请求体')),
                ('expected_status', models.PositiveSmallIntegerField(default=200, verbose_name='预期状态码')),
                ('assertions', models.JSONField(blank=True, default=list, verbose_name='JSON 字段断言')),
                ('max_elapsed_ms', models.PositiveIntegerField(default=0, verbose_name='响应时间上限（毫秒）')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testcases.testcase', verbose_name='关联平台测试用例')),
            ],
        ),
        migrations.CreateModel(
            name='APIEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('base_url', models.CharField(max_length=500, verbose_name='服务地址')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='公共请求头')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='环境变量')),
                ('secret_headers_encrypted', models.TextField(blank=True)),
                ('timeout', models.PositiveSmallIntegerField(default=10, verbose_name='单条超时（秒）')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
            ],
        ),
        migrations.CreateModel(
            name='APIRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment_name', models.CharField(max_length=100)),
                ('submission_token', models.UUIDField()),
                ('snapshot_encrypted', models.TextField()),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('cancel_requested', '正在停止'), ('completed', '已完成'), ('cancelled', '已停止'), ('interrupted', '执行中断')], default='queued', max_length=24)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
                ('test_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testruns.testrun')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='APIResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', '未执行'), ('passed', '通过'), ('failed', '断言失败'), ('error', '请求异常'), ('skipped', '未执行（已停止）')], default='pending', max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('elapsed_ms', models.PositiveIntegerField(null=True)),
                ('request_summary', models.JSONField(default=dict)),
                ('response_summary', models.TextField(blank=True)),
                ('checks', models.JSONField(default=list)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('writeback', models.CharField(blank=True, max_length=500)),
                ('started', models.DateTimeField(null=True)),
                ('completed', models.DateTimeField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai_assistant.apirun')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddIndex(
            model_name='apirun',
            index=models.Index(fields=['status', 'created'], name='api_run_queue'),
        ),
        migrations.AddConstraint(
            model_name='apirun',
            constraint=models.UniqueConstraint(fields=('owner', 'submission_token'), name='unique_api_submission'),
        ),
        migrations.AddConstraint(
            model_name='apiresult',
            constraint=models.UniqueConstraint(fields=('run', 'position'), name='unique_api_run_position'),
        ),
    ]
