# Generated by Django 6.0.8 on 2026-09-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0018_api_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='extracts',
            field=models.JSONField(blank=True, default=dict, verbose_name='响应变量提取'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='执行顺序'),
        ),
        migrations.AddField(
            model_name='apirun',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='ai_assistant.apirun'),
        ),
        migrations.AlterField(
            model_name='apiresult',
            name='status',
            field=models.CharField(choices=[('pending', '未执行'), ('passed', '通过'), ('failed', '断言失败'), ('error', '请求异常'), ('skipped', '已跳过')], default='pending', max_length=16),
        ),
    ]
