# Generated by Django 6.0.8 on 2026-09-25 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0019_api_chained_execution'),
        ('management', '0013_remove_initial_qa_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apirun',
            name='trigger',
            field=models.CharField(choices=[('manual', '手动'), ('schedule', '定时'), ('ci', 'CI')], default='manual', max_length=12),
        ),
        migrations.CreateModel(
            name='APISuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套件名称')),
                ('case_ids', models.JSONField(default=list)),
                ('stop_on_failure', models.BooleanField(default=False, verbose_name='失败后停止')),
                ('share_cookies', models.BooleanField(default=False, verbose_name='本次执行共享 Cookie')),
                ('schedule_enabled', models.BooleanField(default=False, verbose_name='启用定时执行')),
                ('interval_minutes', models.PositiveIntegerField(default=60, verbose_name='执行间隔（分钟）')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次执行时间')),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('ci_token_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('ci_token_expires', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_assistant.apienvironment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
            ],
        ),
        migrations.AddField(
            model_name='apirun',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ai_assistant.apisuite'),
        ),
    ]
