# Generated by Django 6.0.8 on 2026-09-25 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0022_case_result_links'),
        ('management', '0013_remove_initial_qa_contact'),
        ('testcases', '0024_alter_testcase_extra_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='operation',
            field=models.CharField(choices=[('api_case_generation', 'AI 生成接口用例'), ('requirement_analysis', '需求分析'), ('test_case_generation', '生成测试用例'), ('coverage_analysis', '覆盖率分析'), ('coverage_supplement', '补充覆盖缺口'), ('test_case_review', '测试用例评审'), ('test_run_analysis', '测试运行分析'), ('defect_draft_generation', '生成缺陷草稿'), ('test_report_generation', '生成测试报告'), ('connection_test', '模型连接测试')], max_length=40, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='operation',
            field=models.CharField(choices=[('api_case_generation', 'AI 生成接口用例'), ('requirement_analysis', '需求分析'), ('test_case_generation', '生成测试用例'), ('coverage_analysis', '覆盖率分析'), ('coverage_supplement', '补充覆盖缺口'), ('test_case_review', '测试用例评审'), ('test_run_analysis', '测试运行分析'), ('defect_draft_generation', '生成缺陷草稿'), ('test_report_generation', '生成测试报告'), ('connection_test', '模型连接测试'), ('other', '其他')], max_length=40, verbose_name='操作类型'),
        ),
        migrations.CreateModel(
            name='APIAIRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('submission_token', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('input_encrypted', models.TextField()),
                ('generated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testcases.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
                ('target_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testcases.testcase')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='APIAIDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('configuration', models.JSONField(default=dict)),
                ('review_notes', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('api_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.apicase')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='ai_assistant.apiairequest')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddConstraint(
            model_name='apiairequest',
            constraint=models.UniqueConstraint(fields=('owner', 'submission_token'), name='unique_api_ai_submission'),
        ),
        migrations.AddConstraint(
            model_name='apiaidraft',
            constraint=models.UniqueConstraint(fields=('request', 'position'), name='unique_api_ai_position'),
        ),
    ]
