# Generated by Django 6.0.8 on 2026-09-26 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0023_api_ai_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinstructionprofile',
            name='operation',
            field=models.CharField(choices=[('all', '所有需求任务'), ('requirement_analysis', '需求分析'), ('test_case_generation', '生成测试用例'), ('dev_task_breakdown', '拆分开发任务')], default='all', max_length=32, verbose_name='适用任务'),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='operation',
            field=models.CharField(choices=[('api_case_generation', 'AI 生成接口用例'), ('requirement_analysis', '需求分析'), ('test_case_generation', '生成测试用例'), ('dev_task_breakdown', '拆分开发任务'), ('coverage_analysis', '覆盖率分析'), ('coverage_supplement', '补充覆盖缺口'), ('test_case_review', '测试用例评审'), ('test_run_analysis', '测试运行分析'), ('defect_draft_generation', '生成缺陷草稿'), ('test_report_generation', '生成测试报告'), ('connection_test', '模型连接测试')], max_length=40, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='operation',
            field=models.CharField(choices=[('api_case_generation', 'AI 生成接口用例'), ('requirement_analysis', '需求分析'), ('test_case_generation', '生成测试用例'), ('dev_task_breakdown', '拆分开发任务'), ('coverage_analysis', '覆盖率分析'), ('coverage_supplement', '补充覆盖缺口'), ('test_case_review', '测试用例评审'), ('test_run_analysis', '测试运行分析'), ('defect_draft_generation', '生成缺陷草稿'), ('test_report_generation', '生成测试报告'), ('connection_test', '模型连接测试'), ('other', '其他')], max_length=40, verbose_name='操作类型'),
        ),
        migrations.CreateModel(
            name='AIDevTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='顺序')),
                ('task_number', models.CharField(blank=True, max_length=50, verbose_name='任务编号')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('module', models.CharField(blank=True, max_length=200, verbose_name='涉及模块')),
                ('description', models.TextField(blank=True, verbose_name='开发说明')),
                ('acceptance', models.TextField(blank=True, verbose_name='验收标准')),
                ('priority', models.CharField(default='P3', max_length=8, verbose_name='优先级')),
                ('estimate_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='预估工时（小时）')),
                ('status', models.CharField(choices=[('todo', '待开始'), ('doing', '开发中'), ('done', '已完成'), ('blocked', '阻塞')], db_index=True, default='todo', max_length=16, verbose_name='状态')),
                ('requirement_version', models.PositiveIntegerField(default=1, verbose_name='来源需求版本')),
                ('needs_update', models.BooleanField(default=False, verbose_name='需要随需求更新')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_dev_tasks', to=settings.AUTH_USER_MODEL, verbose_name='所属账号')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_tasks', to='ai_assistant.airequest', verbose_name='所属需求')),
            ],
            options={
                'verbose_name': '开发任务单',
                'verbose_name_plural': '开发任务单',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['owner', 'status'], name='ai_dev_task_owner_status')],
            },
        ),
    ]
