# Generated by Django 6.0.8 on 2026-09-26 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0024_alter_aiinstructionprofile_operation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aidevtask',
            options={'ordering': ('position', 'id'), 'permissions': (('split_devtask', '可以拆分开发任务单'), ('assign_devtask', '可以指派开发任务单')), 'verbose_name': '开发任务单', 'verbose_name_plural': '开发任务单'},
        ),
        migrations.AlterModelOptions(
            name='airequest',
            options={'permissions': (('manage_members', '可以管理产品成员与角色'), ('manage_requirement', '可以编辑与删除产品内他人的需求')), 'verbose_name': 'AI请求', 'verbose_name_plural': 'AI请求'},
        ),
        migrations.AlterModelOptions(
            name='aitestreport',
            options={'ordering': ('-created',), 'permissions': (('approve_aireport', '可以审批 AI 测试报告'),), 'verbose_name': 'AI 测试报告', 'verbose_name_plural': 'AI 测试报告'},
        ),
        migrations.AddField(
            model_name='aidevtask',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='指派时间'),
        ),
        migrations.AddField(
            model_name='aidevtask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_dev_tasks', to=settings.AUTH_USER_MODEL, verbose_name='指派人'),
        ),
        migrations.AddField(
            model_name='aidevtask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dev_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddIndex(
            model_name='aidevtask',
            index=models.Index(fields=['assignee', 'status'], name='ai_dev_task_assignee_status'),
        ),
    ]
