# Generated by Django 6.0.8 on 2026-09-26 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clean_gate_rules(apps, schema_editor):
    """门禁规则从「账号级」改成「产品级」之前整理存量数据。

    - product 为空的老规则映射不到任何产品（新字段必填），删掉；
    - 同一产品若有多条（老规则按 owner 去重，不同人可能各配一条），只保留最新
      修改的那条，否则后面那条唯一约束建不起来。
    """
    AIReleaseGateRule = apps.get_model("ai_assistant", "AIReleaseGateRule")
    AIReleaseGateRule.objects.filter(product__isnull=True).delete()
    seen = set()
    for rule in AIReleaseGateRule.objects.order_by("-updated", "-pk"):
        if rule.product_id in seen:
            rule.delete()
        else:
            seen.add(rule.product_id)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0025_alter_aidevtask_options_alter_airequest_options_and_more'),
        ('management', '0013_remove_initial_qa_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clean_gate_rules, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='aireleasegaterule',
            name='unique_ai_gate_rule',
        ),
        migrations.AddField(
            model_name='aireleasegaterule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_release_gate_rules_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='gate_waive_reason',
            field=models.TextField(blank=True, verbose_name='风险放行理由'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='gate_waived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='风险放行时间'),
        ),
        migrations.AddField(
            model_name='aitestreport',
            name='gate_waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_waived_ai_test_reports', to=settings.AUTH_USER_MODEL, verbose_name='风险放行人'),
        ),
        migrations.AlterField(
            model_name='aireleasegaterule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_release_gate_rules', to='management.product', verbose_name='产品'),
        ),
        migrations.AddConstraint(
            model_name='aireleasegaterule',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_ai_gate_rule'),
        ),
        migrations.RemoveField(
            model_name='aireleasegaterule',
            name='owner',
        ),
    ]
