# Generated by Django 6.0.8 on 2026-09-26 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0026_remove_aireleasegaterule_unique_ai_gate_rule_and_more'),
        ('management', '0013_remove_initial_qa_contact'),
        ('testruns', '0020_testexecutiontag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apirun',
            name='heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='心跳时间'),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='status',
            field=models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('cancel_requested', '正在取消'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('interrupted', '中断')], default='queued', max_length=24, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['status', 'heartbeat'], name='ai_job_heartbeat'),
        ),
        migrations.AddIndex(
            model_name='apirun',
            index=models.Index(fields=['status', 'heartbeat'], name='api_run_heartbeat'),
        ),
    ]
