# Generated by Django 6.0.8 on 2026-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0027_apirun_heartbeat_alter_aijob_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresourceassignment',
            name='resource_type',
            field=models.CharField(choices=[('requirement', '需求'), ('case', '测试用例'), ('plan', '测试计划'), ('web_case', 'Web 自动化用例'), ('api_case', '接口自动化用例')], max_length=20, verbose_name='资源类型'),
        ),
        migrations.AlterField(
            model_name='projectresourcefolder',
            name='resource_type',
            field=models.CharField(choices=[('requirement', '需求'), ('case', '测试用例'), ('plan', '测试计划'), ('web_case', 'Web 自动化用例'), ('api_case', '接口自动化用例')], max_length=20, verbose_name='资源类型'),
        ),
    ]
