# Generated by Django 6.0.8 on 2026-10-02 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0029_suite_datasets'),
        ('testruns', '0020_testexecutiontag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('web', 'Web'), ('api', '接口')], max_length=8)),
                ('source_id', models.UUIDField()),
                ('results', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ai_assistant.aitestreport')),
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='testruns.testrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'source_id'), name='unique_automation_archive')],
            },
        ),
    ]
